asyncOnly: true
exit: true
timeout: 8000

extension:
  - 'ts'
require:
  - 'ts-node/register'
  - 'test/setup.ts'
loader:
  - 'ts-node/esm'
watch-ignore:
  - '.*'
  - 'node_modules'
  - 'coverage'

spec:
  - 'test/index.ts'
