sudo: false

branches:
  only:
    - master
    - 0.5.x
    - next

os:
  - linux
  - osx

language: node_js

node_js:
  - v8

before_script: npm install -g gulp

script: npm run test

#after_success: npm run coverage
