sudo: false

branches:
  only:
    - master
    - 0.5.x

language: node_js

node_js:
  - v8
  - v7
  - v6

before_script: npm install -g gulp

script: npm run test

#after_success: npm run coverage

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
  yarn: true
