language: node_js

node_js:
  - v8
  - v7
  - v6

before_script:
  - npm install -g gulp

script:
  - gulp

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
  yarn: true
