branches:
  only:
    - master

language: node_js

install:
  - yarn

node_js:
  - '16'
  - '14'
  - '12'
  - '10'

before_script:
  - yarn
  - cd packages/balm-core && yarn
  - cd ../..

script:
  - yarn test

after_success: yarn coverage
