sudo: false

branches:
  only:
    - master

language: node_js

node_js:
  - '14'
  - '12'
  - '10'

before_script:
  - npm install -g gulp-cli

script:
  - node --version && npm --version
  - npm test

after_success: npm run coverage
