sudo: false

branches:
  only:
    - master

language: node_js

node_js:
  - v8
  - v7
  - v6

before_script:
  - npm install -g bower
  - npm install -g gulp-cli

script: npm run test

#after_success: npm run coverage
