version: "{build}"

branches:
  only:
    - master
    - next

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "8"
#    - nodejs_version: "7"
#    - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - npm install -g gulp
  - npm install

build: off

test_script:
  - npm run test
