environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"

platform:
  - x86
  - x64

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install -g gulp
  - npm install

test_script:
  - gulp
