declare module 'connect-history-api-fallback';
declare module 'gulp-rev-all';
declare module 'gulp-size';
declare module 'less';
declare module 'modernizr';
declare module 'postcss-import';
declare module 'postcss-preset-env';
declare module 'ssh2';
declare module 'vinyl-sourcemaps-apply';
