"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ASSETS_KEYS = ['css', 'js', 'img', 'font', 'media'];
exports.ASSETS_KEYS = ASSETS_KEYS;
var ASYNC_SCRIPTS = 'async';
exports.ASYNC_SCRIPTS = ASYNC_SCRIPTS;
var STATIC_ASSETS = 'assets';
exports.STATIC_ASSETS = STATIC_ASSETS;
var INJECT_HASHNAME = '[contenthash:8]';
exports.INJECT_HASHNAME = INJECT_HASHNAME;
var HMR_PATH = '/__balm_hmr';
exports.HMR_PATH = HMR_PATH;
