"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var path_1 = __importDefault(require("path"));
var gulp_1 = __importDefault(require("gulp"));
var gulp_load_plugins_1 = __importDefault(require("gulp-load-plugins"));
var browser_sync_1 = __importDefault(require("browser-sync"));
var webpack_1 = __importDefault(require("webpack"));
var through2_1 = __importDefault(require("through2"));
var plugin_error_1 = __importDefault(require("plugin-error"));
global.path = path_1.default;
global.gulp = gulp_1.default;
global.$ = gulp_load_plugins_1.default();
global.server = browser_sync_1.default.create();
global.webpack = webpack_1.default;
global.through2 = through2_1.default;
global.PluginError = plugin_error_1.default;
global.BalmJS = {};
